### ISSUE TITLE
Current State of Maintainence

### ISSUE THREAD

**Issue by alexlafroscia** [sir-dunxalot/ember-new-relic#26]
Is this addon being actively maintained?

If not, would you be willing to open up the scope of ownership to a few people? @jasonmit and I have been working on his fork, where we got things working again and made a bunch of clean-up improvements. I would love to upstream these changes, but there hasn't been any activity on this repo in the last year.

We'd love to take over support!

**Comment by sir-dunxalot** [comment]
Hi, I am going to update this library soon. I don't put a lot of time into this addon but, until recently, there also weren't many issues and updates needed (since NR seems to move slow too).

I see one PR from @jasonmit so if you have other changes that you'd like to have release, feel free to open a PR and we can get the improvements on master!

Thanks for your patience. Am happy to add a collaborator to this project if that is of interest but, as I mentioned, there hasn't ever been too much to do! :)
